name: CI/CD ClimaHub

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependências
        run: npm install

      - name: Rodar lint
        run: npm run lint

      - name: Criar arquivo .env
        run: echo "VITE_WEATHERBIT_API_KEY=${{ secrets.VITE_WEATHERBIT_API_KEY }}" > .env
      - name: Build do projeto
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependências
        run: npm install

      - name: Criar arquivo .env
        run: echo "VITE_WEATHERBIT_API_KEY=${{ secrets.VITE_WEATHERBIT_API_KEY }}" > .env
      - name: Build do projeto
        run: npm run build

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./dist
